### PR TITLE
Portuguese ptpt translation of GLOSSARY.md

### PR DESCRIPTION
**Pull request by nunojesus**
I translated this file into Portuguese from Portugal.
Please let me know if what I've done is alright. 
I created a new file of the "GLOSSARY.md" in "open-guide/ptpt/" 
Greetings!

### CODE REVIEW

**Comment by xuv** [comment]
This is great. Thanks for taking this initiative. 
Is there a reason you've named the directory `ptpt` and not just `pt`?

**Comment by nunojesus** [comment]
Hi, I named ptpt, because is Portuguese from Portugal.
Brazilian Portuguese is ptbr.
Greetings

**Comment by xuv** [comment]
Ok, thank you.

Pardon my lack of knowledge, but in this particular case and the context of this book, is there a huge difference between Portuguese from Portugal and from Brazil. Does it make sense to separate the translation?

So you know, we have written the book in some "international english" and apart from one of the proof reader, it was definitely not the language we were raised with.

I'll let you be the judge if there needs to be 2 different versions of the book, one for Portugal and one for Brazil. But if there is not critical differences between the two of them around the subject we are talking about, I would advocate for just one `pt` folder... It will be easier to maintain.

Let me know what you think.

**Comment by nunojesus** [comment]
Hello, between Portuguese of Portugal and Portuguese of Brazil there are small differences, we have some words that are different, but nothing special.
So there may be only one folder for the Portuguese translation.

**Comment by xuv** [comment]
That's great to hear. I'll merge it and then chang the folder name then.

**Comment by nunojesus** [comment]
Ok

**Comment by xuv** [comment]
@nunojesus I've moved both your files in a pt subdirectory. Please, put all future translations in that directory. And thx for the great work.

**Pull request merged**
